# Generated by Django 3.0.7 on 2020-06-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='course',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
